### ISSUE TITLE
CShuster feedback milestone3

### ISSUE THREAD

**Issue by shusterc** [UBC-MDS/Crime_Data#19]
- no description of the dataset: what am i interested in this? what is this about?
- map doesn't respond to city selection: consider have conditionalPanel on the side for tabs
- year range: can only change the upper limit (lower limit fixed) but user may be interested in some range in the middle. after explanation this was meant to be use as a scroll bar thus i would recommend removing the blue highlight
- city specific  tab: 
    - Can only select city, not crime, why? 
    - Also what are the blue bars at the bottom for - richie explained its the population size to show relationship between crime rate and the population size of a city. I would recommend to create a second graph for population size so its easier to understand what data is plotted, also include blurb about why both graphs are shown
- Map tab:
    - recommend changing color of blue circles because the ocean is blue, consider adding a legend to show the user "how much" crime is going on as about to only show relativity.

**Comment by aylapear** [comment]
Thank you shusterc for the feedback on our app. We have implemented some of you suggestions. 
- We have added a description under an info tab and directions on how to use the app. 
- The city selector was removed from the map tab. 
- We are looking into different styles of the year slide bar so it doesn't look like range. 
- Under the city tab we have changed the crime type to a check-box so you can now select the crime type and it will draw that line on the plot. 
- We choose to not move population to a different plot due to spacing issues, but now it is manually selected by the check-boxes and it is more intuitive now that you have to choose to display population. 
- We have changed the colors of the circles to be different for each crime, the tool tip will now show the values for the city.
